package com.jcirmodelsquad.tcjcir.recipes;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import train.common.api.crafting.ITierCraftingManager;
import train.common.core.handlers.AbstractRecipeHandler;
import train.common.library.ItemIDs;

public class PassengerRecipes extends AbstractRecipeHandler {
    public PassengerRecipes(ITierCraftingManager cm)
    {
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, WHITE_DYE, new ItemStack(ItemIDs.minecartOBBAR52SeatCoach_Dinette.item, 1), 1);

        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 4), null, null, ORANGE_DYE, new ItemStack(ItemIDs.minecartPSGNRPO_30.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 4), null, null, ORANGE_DYE, new ItemStack(ItemIDs.minecartACFGNRPO_30.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartACFGN60SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 3), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartACFGNDiner_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 3), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartACFGN28SeatCoach_Dinette.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartACFGN1DR_17SeatParlor_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), ORANGE_DYE, new ItemStack(ItemIDs.minecartBuddNYC52SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), null, null, ORANGE_DYE, new ItemStack(ItemIDs.minecartMILWPrewarBaggage.item, 1), 1);
        cm.addRecipe(3, SteelIngot(5), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 2), new ItemStack(ItemIDs.seats.item, 5), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartMILW1935Baggage_Dinette.item, 1), 1);
        cm.addRecipe(3, SteelIngot(5), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartMILW1935Tap_Dinette.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Items.bed, 1), new ItemStack(ItemIDs.seats.item, 5), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartMILW1935Dorm_56SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartMILW1935_48SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 2), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartMILW1935_22SeatParlor.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 2), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartMILW1935_21SeatParlor_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, ORANGE_DYE, new ItemStack(ItemIDs.minecartMILW1935_44SeatCoach_Observation.item, 1), 1);

        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 2), null, new ItemStack(ItemIDs.seats.item, 6), new ItemStack(ItemIDs.passengerFluting.item, 6), BLUE_DYE, new ItemStack(ItemIDs.minecartBuddDome54SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, BLUE_DYE, new ItemStack(ItemIDs.minecartACF_LN_KCS60SeatDividedCoach.item, 1), 1);
        cm.addRecipe(2, SteelIngot(3), TCItemStack(ItemIDs.sixWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 3), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, BLUE_DYE, new ItemStack(ItemIDs.minecartLNCoach2551Series.item, 1), 1);

        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), new ItemStack(ItemIDs.passengerFluting.item, 6), CYAN_DYE, new ItemStack(ItemIDs.minecartBuddATSF48SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, CYAN_DYE, new ItemStack(ItemIDs.minecartPRECOPendulumCoach.item, 1), 1);


        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), LIGHT_GRAY_DYE, new ItemStack(ItemIDs.minecartBuddCBQ52SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 2), null, new ItemStack(ItemIDs.seats.item, 6), new ItemStack(ItemIDs.passengerFluting.item, 6), LIGHT_GRAY_DYE, new ItemStack(ItemIDs.minecartBuddCBQDome50SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), null, new ItemStack(ItemIDs.passengerFluting.item, 4), LIGHT_GRAY_DYE, new ItemStack(ItemIDs.minecartPSSOUBaggage.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemIDs.passengerFluting.item, 4), LIGHT_GRAY_DYE, new ItemStack(ItemIDs.minecartPSSOURPO_30.item, 1), 1);

        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 6), null, GREEN_DYE, new ItemStack(ItemIDs.minecartOB84SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 7), null, GREEN_DYE, new ItemStack(ItemIDs.minecartOB92SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 6), null, GREEN_DYE, new ItemStack(ItemIDs.minecartOBNHGrillCar.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, GREEN_DYE, new ItemStack(ItemIDs.minecartOBNHLounge5107.item, 1), 1);
        cm.addRecipe(2, SteelIngot(4), TCItemStack(ItemIDs.fourWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 3), null, null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), null, null, GREEN_DYE, new ItemStack(ItemIDs.minecartOBHWNH5570_5589Baggage.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 6), null, GREEN_DYE, new ItemStack(ItemIDs.minecartOB76SeatDividedCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 4), null, GREEN_DYE, new ItemStack(ItemIDs.minecartOBBaggage_52SeatDividedCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 4), null, null, GREEN_DYE, new ItemStack(ItemIDs.minecartOBRPO15.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, GREEN_DYE, new ItemStack(ItemIDs.minecartOB24SeatCoach_Dinette.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), null, null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), null, null, GREEN_DYE, new ItemStack(ItemIDs.minecartNSCCNBaggage.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 4), new ItemStack(ItemIDs.passengerFluting.item, 6), GREEN_DYE, new ItemStack(ItemIDs.minecartPSFNCCBaggage_Dinette.item, 1), 1);
        cm.addRecipe(2, SteelIngot(1), TCItemStack(ItemIDs.interurbanTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), new ItemStack(ItemIDs.trolleyPole.item, 2), TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, GREEN_DYE, new ItemStack(ItemIDs.minecartW_A11.item, 1), 1);
        cm.addRecipe(2, SteelIngot(1), TCItemStack(ItemIDs.interurbanTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), new ItemStack(ItemIDs.trolleyPole.item, 2), TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 2), new ItemStack(ItemIDs.seats.item, 3), null, GREEN_DYE, new ItemStack(ItemIDs.minecartW_A55_Combine.item, 1), 1);
        cm.addRecipe(2, SteelIngot(1), TCItemStack(ItemIDs.interurbanTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), new ItemStack(ItemIDs.trolleyPole.item, 2), TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, GREEN_DYE, new ItemStack(ItemIDs.minecartW_A55.item, 1), 1);
        cm.addRecipe(2, SteelIngot(4), TCItemStack(ItemIDs.sixWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 4), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 7), null, GREEN_DYE, new ItemStack(ItemIDs.minecartACF_SP_98seatcoach.item, 1), 1);

        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 2), PURPLE_DYE, new ItemStack(ItemIDs.minecartPS54SeatCoach_Lounge_1950.item, 1), 1);

        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPS52seatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 3), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPScombine.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPSCenterDiner.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPSDamnitAnotherDiner.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 1), null, null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPS73Baggage.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), null, null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPS85Baggage.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Items.bed, 1), new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPSSleeper565.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 1), SteelIngot(1), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPSRPOPM.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 1), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPSRPO.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPSLunchCounter_Lounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 3), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPS30SeatParlor.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPS54SeatCoach_Lounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 6), new ItemStack(ItemIDs.passengerFluting.item, 2), BLUE_DYE, new ItemStack(ItemIDs.minecartPS58SeatCoach_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), BLUE_DYE, new ItemStack(ItemIDs.minecartBuddRDG56SeatCoachLounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), new ItemStack(ItemIDs.passengerFluting.item, 6), BLUE_DYE, new ItemStack(ItemIDs.minecartBuddRDGDiner_Lounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), BLUE_DYE, new ItemStack(ItemIDs.minecartBuddRDG56SeatCoach_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 3), null, BLUE_DYE, new ItemStack(ItemIDs.minecartPSCEIRPO15_Baggage_LC_Lounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 4), null, BLUE_DYE, new ItemStack(ItemIDs.minecartPSCEIRPO15_Baggage_38SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, BLUE_DYE, new ItemStack(ItemIDs.minecartPSCEI60SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(5), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, BLUE_DYE, new ItemStack(ItemIDs.minecartPSCEIDiner.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 2), null, BLUE_DYE, new ItemStack(ItemIDs.minecartPSCEI1DR28SeatParlorObservation.item, 1), 1);

        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 3), new ItemStack(ItemIDs.passengerFluting.item, 4), MAGENTA_DYE, new ItemStack(ItemIDs.minecartPSBMCombine.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 4), MAGENTA_DYE, new ItemStack(ItemIDs.minecartPSBM56SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), new ItemStack(ItemIDs.passengerFluting.item, 4), MAGENTA_DYE, new ItemStack(ItemIDs.minecartPSBMDiner_Lounge.item, 1), 1);


        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Items.bed, 1), new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 2), YELLOW_DYE, new ItemStack(ItemIDs.minecartPSSleeper565DRGW.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW56SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW48SeatCoachLounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 2), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW20SeatCoachLounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 3), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW36SeatCoach_Dinette.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(5), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW56SeatDiner.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(5), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW48SeatDiner.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(5), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 2), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW1DR_22SeatParlor.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(5), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Items.bed, 1), new ItemStack(ItemIDs.seats.item, 2), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW16_1_3Sleeper.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 2), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW12SeatParlor_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(1), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 4), null, null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNWRPO15.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 4), null, null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNWRPO60.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 4), null, null, YELLOW_DYE, new ItemStack(ItemIDs.minecartACFUPRPO60.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 3), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNWBaggage_LC_Lounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 3), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNWRPO15_Baggage_LC_Lounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(4), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), new ItemStack(ItemIDs.seats.item, 4), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNWBaggage_LC_Diner.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 2), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW20SeatCoachLounge_1959.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(5), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNWCommuterLounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 3), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartPSCNW27SeatParlor_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), YELLOW_DYE, new ItemStack(ItemIDs.minecartBuddATSF52SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), YELLOW_DYE, new ItemStack(ItemIDs.minecartBuddATSF50SeatCoachObservation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 3), new ItemStack(ItemIDs.passengerFluting.item, 6), YELLOW_DYE, new ItemStack(ItemIDs.minecartBuddATSF34SeatParlorObservation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), YELLOW_DYE, new ItemStack(ItemIDs.minecartBuddATSF58SeatCoachObservation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 4), YELLOW_DYE, new ItemStack(ItemIDs.minecartPSATSF50SeatCoachObservation.item, 1), 1);
        cm.addRecipe(2, SteelIngot(4), TCItemStack(ItemIDs.sixWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 4), SteelIngot(2), null, null, new ItemStack(Blocks.chest, 3), null, null, YELLOW_DYE, new ItemStack(ItemIDs.minecartDRGWRPO620Series.item, 1), 1);
        cm.addRecipe(2, SteelIngot(4), TCItemStack(ItemIDs.sixWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 4), SteelIngot(2), null, null, new ItemStack(Blocks.chest, 3), null, null, YELLOW_DYE, new ItemStack(ItemIDs.minecartDRGWRPO630Series.item, 1), 1);
        cm.addRecipe(2, SteelIngot(4), TCItemStack(ItemIDs.fourWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 3), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), null, null, YELLOW_DYE, new ItemStack(ItemIDs.minecartDRGWBaggage700Series.item, 1), 1);
        cm.addRecipe(2, SteelIngot(5), TCItemStack(ItemIDs.fourWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 4), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 3), null, null, YELLOW_DYE, new ItemStack(ItemIDs.minecartDRGWBaggage740Series.item, 1), 1);
        cm.addRecipe(2, SteelIngot(4), TCItemStack(ItemIDs.fourWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 3), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartDRGWCoach1000Series.item, 1), 1);
        cm.addRecipe(2, SteelIngot(3), TCItemStack(ItemIDs.fourWheelHeavyweightTruck, 2), TCItemStack(ItemIDs.steelframe, 3), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, YELLOW_DYE, new ItemStack(ItemIDs.minecartDRGWCoach1005Series.item, 1), 1);

        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), BLACK_DYE, new ItemStack(ItemIDs.minecartBuddCNCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), new ItemStack(ItemIDs.passengerFluting.item, 6), BLACK_DYE, new ItemStack(ItemIDs.minecartBuddCNDiner_Lounge.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 6), new ItemStack(ItemIDs.passengerFluting.item, 6), BLACK_DYE, new ItemStack(ItemIDs.minecartBuddCN68SeatCoach_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), new ItemStack(ItemIDs.passengerFluting.item, 6), BLACK_DYE, new ItemStack(ItemIDs.minecartBuddCN39SeatParlor_Observation.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(3), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), BLACK_DYE, new ItemStack(ItemIDs.minecartBuddCN59SeatCoach_Observation.item, 1), 1);

        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), GRAY_DYE, new ItemStack(ItemIDs.minecartBuddCRIP52SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 2), null, new ItemStack(ItemIDs.seats.item, 5), new ItemStack(ItemIDs.passengerFluting.item, 6), GRAY_DYE, new ItemStack(ItemIDs.minecartBuddDome46SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(4), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 1), null, null, TCItemStack(ItemIDs.steelcab, 1), new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemIDs.passengerFluting.item, 6), GRAY_DYE, new ItemStack(ItemIDs.minecartBuddPrewarBaggage.item, 1), 1);
        cm.addRecipe(3, SteelIngot(2), TCItemStack(ItemIDs.fourWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 5), null, GRAY_DYE, new ItemStack(ItemIDs.minecartNYCPrewar56SeatCoach.item, 1), 1);
        cm.addRecipe(3, SteelIngot(3), TCItemStack(ItemIDs.sixWheelLightweightTruck, 2), TCItemStack(ItemIDs.steelframe, 2), SteelIngot(2), null, TCItemStack(ItemIDs.steelcab, 1), null, new ItemStack(ItemIDs.seats.item, 4), null, GRAY_DYE, new ItemStack(ItemIDs.minecartMON_lightweightCoach.item, 1), 1);


    }

}